/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppRole = IDL.Variant({
  'Buyer' : IDL.Null,
  'Foreman' : IDL.Null,
  'Admin' : IDL.Null,
  'Finance' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'volume' : IDL.Nat,
  'parentId' : IDL.Opt(IDL.Nat),
});
export const MaterialRequest = IDL.Record({
  'id' : IDL.Nat,
  'financePrice' : IDL.Opt(IDL.Nat),
  'jobId' : IDL.Nat,
  'buyerPrice' : IDL.Opt(IDL.Nat),
  'finalApproval' : IDL.Bool,
  'materialId' : IDL.Nat,
  'approvedByFinance' : IDL.Bool,
  'quantity' : IDL.Nat,
  'approvedByBuyer' : IDL.Bool,
  'requestedBy' : IDL.Principal,
});
export const Material = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const ProgressRecord = IDL.Record({
  'date' : Time,
  'jobId' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const RAPTemplate = IDL.Record({
  'id' : IDL.Nat,
  'jobs' : IDL.Vec(Job),
  'name' : IDL.Text,
});
export const RealizationReport = IDL.Record({
  'actualPrice' : IDL.Nat,
  'date' : Time,
  'createdBy' : IDL.Principal,
  'materialId' : IDL.Nat,
  'vendorId' : IDL.Nat,
});
export const Vendor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJob' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'addMaterial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addRealizationReport' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'addVendor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'approveMaterialRequestByBuyer' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'approveMaterialRequestByFinance' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'createMaterialRequest' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'createRAPTemplate' : IDL.Func([IDL.Text, IDL.Vec(Job)], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
  'deleteRAPTemplate' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllMaterialRequests' : IDL.Func(
      [],
      [IDL.Vec(MaterialRequest)],
      ['query'],
    ),
  'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'getAllProgressRecords' : IDL.Func([], [IDL.Vec(ProgressRecord)], ['query']),
  'getAllRAPTemplates' : IDL.Func([], [IDL.Vec(RAPTemplate)], ['query']),
  'getAllRealizationReports' : IDL.Func(
      [],
      [IDL.Vec(RealizationReport)],
      ['query'],
    ),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMaterialUsageSummary' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'totalApproved' : IDL.Nat, 'totalRequested' : IDL.Nat })],
      ['query'],
    ),
  'getMyMaterialRequests' : IDL.Func([], [IDL.Vec(MaterialRequest)], ['query']),
  'getPendingBuyerApprovals' : IDL.Func(
      [],
      [IDL.Vec(MaterialRequest)],
      ['query'],
    ),
  'getPendingFinanceApprovals' : IDL.Func(
      [],
      [IDL.Vec(MaterialRequest)],
      ['query'],
    ),
  'getProgressRecordsByJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProgressRecord)],
      ['query'],
    ),
  'getRealizationReportsByMaterial' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RealizationReport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateJob' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateMaterial' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateRAPTemplate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Job)], [], []),
  'updateVendor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppRole = IDL.Variant({
    'Buyer' : IDL.Null,
    'Foreman' : IDL.Null,
    'Admin' : IDL.Null,
    'Finance' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'appRole' : AppRole, 'name' : IDL.Text });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'volume' : IDL.Nat,
    'parentId' : IDL.Opt(IDL.Nat),
  });
  const MaterialRequest = IDL.Record({
    'id' : IDL.Nat,
    'financePrice' : IDL.Opt(IDL.Nat),
    'jobId' : IDL.Nat,
    'buyerPrice' : IDL.Opt(IDL.Nat),
    'finalApproval' : IDL.Bool,
    'materialId' : IDL.Nat,
    'approvedByFinance' : IDL.Bool,
    'quantity' : IDL.Nat,
    'approvedByBuyer' : IDL.Bool,
    'requestedBy' : IDL.Principal,
  });
  const Material = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ProgressRecord = IDL.Record({
    'date' : Time,
    'jobId' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const RAPTemplate = IDL.Record({
    'id' : IDL.Nat,
    'jobs' : IDL.Vec(Job),
    'name' : IDL.Text,
  });
  const RealizationReport = IDL.Record({
    'actualPrice' : IDL.Nat,
    'date' : Time,
    'createdBy' : IDL.Principal,
    'materialId' : IDL.Nat,
    'vendorId' : IDL.Nat,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJob' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'addMaterial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addRealizationReport' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'addVendor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'approveMaterialRequestByBuyer' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'approveMaterialRequestByFinance' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'createMaterialRequest' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'createRAPTemplate' : IDL.Func([IDL.Text, IDL.Vec(Job)], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
    'deleteRAPTemplate' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllMaterialRequests' : IDL.Func(
        [],
        [IDL.Vec(MaterialRequest)],
        ['query'],
      ),
    'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'getAllProgressRecords' : IDL.Func(
        [],
        [IDL.Vec(ProgressRecord)],
        ['query'],
      ),
    'getAllRAPTemplates' : IDL.Func([], [IDL.Vec(RAPTemplate)], ['query']),
    'getAllRealizationReports' : IDL.Func(
        [],
        [IDL.Vec(RealizationReport)],
        ['query'],
      ),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMaterialUsageSummary' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'totalApproved' : IDL.Nat, 'totalRequested' : IDL.Nat })],
        ['query'],
      ),
    'getMyMaterialRequests' : IDL.Func(
        [],
        [IDL.Vec(MaterialRequest)],
        ['query'],
      ),
    'getPendingBuyerApprovals' : IDL.Func(
        [],
        [IDL.Vec(MaterialRequest)],
        ['query'],
      ),
    'getPendingFinanceApprovals' : IDL.Func(
        [],
        [IDL.Vec(MaterialRequest)],
        ['query'],
      ),
    'getProgressRecordsByJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProgressRecord)],
        ['query'],
      ),
    'getRealizationReportsByMaterial' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RealizationReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateJob' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateMaterial' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateRAPTemplate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Job)], [], []),
    'updateVendor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };