/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Buyer' : null } |
  { 'Foreman' : null } |
  { 'Admin' : null } |
  { 'Finance' : null };
export interface Job {
  'id' : bigint,
  'cost' : bigint,
  'name' : string,
  'unit' : string,
  'volume' : bigint,
  'parentId' : [] | [bigint],
}
export interface Material {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'price' : bigint,
}
export interface MaterialRequest {
  'id' : bigint,
  'financePrice' : [] | [bigint],
  'jobId' : bigint,
  'buyerPrice' : [] | [bigint],
  'finalApproval' : boolean,
  'materialId' : bigint,
  'approvedByFinance' : boolean,
  'quantity' : bigint,
  'approvedByBuyer' : boolean,
  'requestedBy' : Principal,
}
export interface ProgressRecord {
  'date' : Time,
  'jobId' : bigint,
  'percentage' : bigint,
}
export interface RAPTemplate {
  'id' : bigint,
  'jobs' : Array<Job>,
  'name' : string,
}
export interface RealizationReport {
  'actualPrice' : bigint,
  'date' : Time,
  'createdBy' : Principal,
  'materialId' : bigint,
  'vendorId' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'appRole' : AppRole, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : bigint,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJob' : ActorMethod<
    [string, bigint, string, bigint, [] | [bigint]],
    undefined
  >,
  'addMaterial' : ActorMethod<[string, string, bigint], undefined>,
  'addRealizationReport' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'addVendor' : ActorMethod<[string, string, string], undefined>,
  'approveMaterialRequestByBuyer' : ActorMethod<
    [bigint, bigint, bigint],
    undefined
  >,
  'approveMaterialRequestByFinance' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserProfile], undefined>,
  'createMaterialRequest' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'createRAPTemplate' : ActorMethod<[string, Array<Job>], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'deleteMaterial' : ActorMethod<[bigint], undefined>,
  'deleteRAPTemplate' : ActorMethod<[bigint], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAllMaterialRequests' : ActorMethod<[], Array<MaterialRequest>>,
  'getAllMaterials' : ActorMethod<[], Array<Material>>,
  'getAllProgressRecords' : ActorMethod<[], Array<ProgressRecord>>,
  'getAllRAPTemplates' : ActorMethod<[], Array<RAPTemplate>>,
  'getAllRealizationReports' : ActorMethod<[], Array<RealizationReport>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMaterialUsageSummary' : ActorMethod<
    [bigint],
    { 'totalApproved' : bigint, 'totalRequested' : bigint }
  >,
  'getMyMaterialRequests' : ActorMethod<[], Array<MaterialRequest>>,
  'getPendingBuyerApprovals' : ActorMethod<[], Array<MaterialRequest>>,
  'getPendingFinanceApprovals' : ActorMethod<[], Array<MaterialRequest>>,
  'getProgressRecordsByJob' : ActorMethod<[bigint], Array<ProgressRecord>>,
  'getRealizationReportsByMaterial' : ActorMethod<
    [bigint],
    Array<RealizationReport>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordProgress' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateJob' : ActorMethod<
    [bigint, string, bigint, string, bigint, [] | [bigint]],
    undefined
  >,
  'updateMaterial' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'updateRAPTemplate' : ActorMethod<[bigint, string, Array<Job>], undefined>,
  'updateVendor' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];