/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Material {
    id: bigint;
    name: string;
    unit: string;
    price: bigint;
}
export interface ProgressRecord {
    date: Time;
    jobId: bigint;
    percentage: bigint;
}
export interface Job {
    id: bigint;
    cost: bigint;
    name: string;
    unit: string;
    volume: bigint;
    parentId?: bigint;
}
export type Time = bigint;
export interface RealizationReport {
    actualPrice: bigint;
    date: Time;
    createdBy: Principal;
    materialId: bigint;
    vendorId: bigint;
}
export interface MaterialRequest {
    id: bigint;
    financePrice?: bigint;
    jobId: bigint;
    buyerPrice?: bigint;
    finalApproval: boolean;
    materialId: bigint;
    approvedByFinance: boolean;
    quantity: bigint;
    approvedByBuyer: boolean;
    requestedBy: Principal;
}
export interface Vendor {
    id: bigint;
    name: string;
    address: string;
    phone: string;
}
export interface RAPTemplate {
    id: bigint;
    jobs: Array<Job>;
    name: string;
}
export interface UserProfile {
    appRole: AppRole;
    name: string;
}
export enum AppRole {
    Buyer = "Buyer",
    Foreman = "Foreman",
    Admin = "Admin",
    Finance = "Finance"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addJob(name: string, volume: bigint, unit: string, cost: bigint, parentId: bigint | null): Promise<void>;
    addMaterial(name: string, unit: string, price: bigint): Promise<void>;
    addRealizationReport(materialId: bigint, actualPrice: bigint, vendorId: bigint): Promise<void>;
    addVendor(name: string, address: string, phone: string): Promise<void>;
    approveMaterialRequestByBuyer(requestId: bigint, price: bigint, quantity: bigint): Promise<void>;
    approveMaterialRequestByFinance(requestId: bigint, finalPrice: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(user: Principal, profile: UserProfile): Promise<void>;
    createMaterialRequest(jobId: bigint, materialId: bigint, quantity: bigint): Promise<void>;
    createRAPTemplate(name: string, jobsList: Array<Job>): Promise<void>;
    deleteJob(id: bigint): Promise<void>;
    deleteMaterial(id: bigint): Promise<void>;
    deleteRAPTemplate(id: bigint): Promise<void>;
    deleteVendor(id: bigint): Promise<void>;
    getAllJobs(): Promise<Array<Job>>;
    getAllMaterialRequests(): Promise<Array<MaterialRequest>>;
    getAllMaterials(): Promise<Array<Material>>;
    getAllProgressRecords(): Promise<Array<ProgressRecord>>;
    getAllRAPTemplates(): Promise<Array<RAPTemplate>>;
    getAllRealizationReports(): Promise<Array<RealizationReport>>;
    getAllVendors(): Promise<Array<Vendor>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMaterialUsageSummary(materialId: bigint): Promise<{
        totalApproved: bigint;
        totalRequested: bigint;
    }>;
    getMyMaterialRequests(): Promise<Array<MaterialRequest>>;
    getPendingBuyerApprovals(): Promise<Array<MaterialRequest>>;
    getPendingFinanceApprovals(): Promise<Array<MaterialRequest>>;
    getProgressRecordsByJob(jobId: bigint): Promise<Array<ProgressRecord>>;
    getRealizationReportsByMaterial(materialId: bigint): Promise<Array<RealizationReport>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordProgress(jobId: bigint, percentage: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateJob(id: bigint, name: string, volume: bigint, unit: string, cost: bigint, parentId: bigint | null): Promise<void>;
    updateMaterial(id: bigint, name: string, unit: string, price: bigint): Promise<void>;
    updateRAPTemplate(id: bigint, name: string, jobsList: Array<Job>): Promise<void>;
    updateVendor(id: bigint, name: string, address: string, phone: string): Promise<void>;
}
import type { AppRole as _AppRole, Job as _Job, MaterialRequest as _MaterialRequest, RAPTemplate as _RAPTemplate, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addJob(arg0: string, arg1: bigint, arg2: string, arg3: bigint, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addMaterial(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaterial(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaterial(arg0, arg1, arg2);
            return result;
        }
    }
    async addRealizationReport(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRealizationReport(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRealizationReport(arg0, arg1, arg2);
            return result;
        }
    }
    async addVendor(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVendor(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVendor(arg0, arg1, arg2);
            return result;
        }
    }
    async approveMaterialRequestByBuyer(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMaterialRequestByBuyer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMaterialRequestByBuyer(arg0, arg1, arg2);
            return result;
        }
    }
    async approveMaterialRequestByFinance(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMaterialRequestByFinance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMaterialRequestByFinance(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMaterialRequest(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMaterialRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMaterialRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async createRAPTemplate(arg0: string, arg1: Array<Job>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRAPTemplate(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRAPTemplate(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaterial(arg0);
            return result;
        }
    }
    async deleteRAPTemplate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRAPTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRAPTemplate(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async getAllJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMaterialRequests(): Promise<Array<MaterialRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMaterialRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMaterialRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMaterials(): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMaterials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMaterials();
            return result;
        }
    }
    async getAllProgressRecords(): Promise<Array<ProgressRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProgressRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProgressRecords();
            return result;
        }
    }
    async getAllRAPTemplates(): Promise<Array<RAPTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRAPTemplates();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRAPTemplates();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRealizationReports(): Promise<Array<RealizationReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRealizationReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRealizationReports();
            return result;
        }
    }
    async getAllVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVendors();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterialUsageSummary(arg0: bigint): Promise<{
        totalApproved: bigint;
        totalRequested: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialUsageSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialUsageSummary(arg0);
            return result;
        }
    }
    async getMyMaterialRequests(): Promise<Array<MaterialRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMaterialRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMaterialRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingBuyerApprovals(): Promise<Array<MaterialRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingBuyerApprovals();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingBuyerApprovals();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingFinanceApprovals(): Promise<Array<MaterialRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFinanceApprovals();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFinanceApprovals();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressRecordsByJob(arg0: bigint): Promise<Array<ProgressRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressRecordsByJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressRecordsByJob(arg0);
            return result;
        }
    }
    async getRealizationReportsByMaterial(arg0: bigint): Promise<Array<RealizationReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRealizationReportsByMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRealizationReportsByMaterial(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordProgress(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordProgress(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJob(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateMaterial(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaterial(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaterial(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateRAPTemplate(arg0: bigint, arg1: string, arg2: Array<Job>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRAPTemplate(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRAPTemplate(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateVendor(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_AppRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_MaterialRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaterialRequest): MaterialRequest {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RAPTemplate_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RAPTemplate): RAPTemplate {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cost: bigint;
    name: string;
    unit: string;
    volume: bigint;
    parentId: [] | [bigint];
}): {
    id: bigint;
    cost: bigint;
    name: string;
    unit: string;
    volume: bigint;
    parentId?: bigint;
} {
    return {
        id: value.id,
        cost: value.cost,
        name: value.name,
        unit: value.unit,
        volume: value.volume,
        parentId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    financePrice: [] | [bigint];
    jobId: bigint;
    buyerPrice: [] | [bigint];
    finalApproval: boolean;
    materialId: bigint;
    approvedByFinance: boolean;
    quantity: bigint;
    approvedByBuyer: boolean;
    requestedBy: Principal;
}): {
    id: bigint;
    financePrice?: bigint;
    jobId: bigint;
    buyerPrice?: bigint;
    finalApproval: boolean;
    materialId: bigint;
    approvedByFinance: boolean;
    quantity: bigint;
    approvedByBuyer: boolean;
    requestedBy: Principal;
} {
    return {
        id: value.id,
        financePrice: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.financePrice)),
        jobId: value.jobId,
        buyerPrice: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.buyerPrice)),
        finalApproval: value.finalApproval,
        materialId: value.materialId,
        approvedByFinance: value.approvedByFinance,
        quantity: value.quantity,
        approvedByBuyer: value.approvedByBuyer,
        requestedBy: value.requestedBy
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    jobs: Array<_Job>;
    name: string;
}): {
    id: bigint;
    jobs: Array<Job>;
    name: string;
} {
    return {
        id: value.id,
        jobs: from_candid_vec_n11(_uploadFile, _downloadFile, value.jobs),
        name: value.name
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: _AppRole;
    name: string;
}): {
    appRole: AppRole;
    name: string;
} {
    return {
        appRole: from_candid_AppRole_n24(_uploadFile, _downloadFile, value.appRole),
        name: value.name
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Buyer: null;
} | {
    Foreman: null;
} | {
    Admin: null;
} | {
    Finance: null;
}): AppRole {
    return "Buyer" in value ? AppRole.Buyer : "Foreman" in value ? AppRole.Foreman : "Admin" in value ? AppRole.Admin : "Finance" in value ? AppRole.Finance : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaterialRequest>): Array<MaterialRequest> {
    return value.map((x)=>from_candid_MaterialRequest_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RAPTemplate>): Array<RAPTemplate> {
    return value.map((x)=>from_candid_RAPTemplate_n19(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Job_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Job): _Job {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cost: bigint;
    name: string;
    unit: string;
    volume: bigint;
    parentId?: bigint;
}): {
    id: bigint;
    cost: bigint;
    name: string;
    unit: string;
    volume: bigint;
    parentId: [] | [bigint];
} {
    return {
        id: value.id,
        cost: value.cost,
        name: value.name,
        unit: value.unit,
        volume: value.volume,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none()
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: AppRole;
    name: string;
}): {
    appRole: _AppRole;
    name: string;
} {
    return {
        appRole: to_candid_AppRole_n6(_uploadFile, _downloadFile, value.appRole),
        name: value.name
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    Buyer: null;
} | {
    Foreman: null;
} | {
    Admin: null;
} | {
    Finance: null;
} {
    return value == AppRole.Buyer ? {
        Buyer: null
    } : value == AppRole.Foreman ? {
        Foreman: null
    } : value == AppRole.Admin ? {
        Admin: null
    } : value == AppRole.Finance ? {
        Finance: null
    } : value;
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Job>): Array<_Job> {
    return value.map((x)=>to_candid_Job_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
